entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

#certificatesResolvers:
#  myresolver:
#    acme:
#      email: ayush@gmail.com
#      storage: acme.json
#      httpChallenge:
#        entryPoint: web

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true

log:
  level: DEBUG
